title: Vera Jans
email: verajans55555@gmail.com
description: Янс Вера Районирована - cкульптор, художник
baseurl: "/jans.io" # the subpath of your site, e.g. /blog
url: "https://thekit3.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
collections:
  sculpture:
    output: true
  painting:
    output: true
  projects:
    output: true
